feat/postRouters
GammaGammaRay/projeto19-linkr-api pull request #5
Opened 2023-08-18 16:12 UTC by maariaclaara

Comecei ontem e hoje adiantei o que tinha de dados, mas acredito q teremos que mexer nas tables, já que está faltando informações q preciso obter no GET.

2023-08-18 18:22 UTC, PPAKruNN commented on src/repositories/posts.repository.js
> +      `SELECT COUNT(*) AS "countPosts" FROM posts WHERE "createdAt" >= $1
Não tenho certeza se o banco consegue lidar com o ">=". Ele consegue?

2023-08-18 18:24 UTC, PPAKruNN commented on src/controllers/posts.controllers.js
> +      const totalPosts = rows[0].amountPosts;
totalPosts está com o número de posts recentes.
A variavel que possui a quantidade total é "numberPosts".

2023-08-18 18:26 UTC, PPAKruNN commented on src/controllers/posts.controllers.js
> +      const { rows } = await recentPosts();
Dentro do próprio repository, ao inves de return db.query(), voce poderia já ter retornado o número de posts ao invés de tratá-los aqui do lado de fora.
Ou seja, dentro do repository, retornar a resposta da db.query acessando .rows[0].amountPosts.

2023-08-18 18:28 UTC, jaypeenascimento commented on src/controllers/posts.controllers.js
> +        nextUrl,
Real muito maneiro como tu fez isso de retornar a proxima pro front. Curti demais!

Em termos práticos, quem normalmente faz calcula qual a url das páginas é o front, mas achei sua ideia real muito boa! :D

2023-08-18 18:34 UTC, PPAKruNN commented on src/controllers/posts.controllers.js
> +        totalPosts,
Se o objetivo de totalposts é indicar quantos posts existem no DB inteiro, então ele está com o valor errado no momento (Como eu indiquei no comentário da criação dele).

Caso o objetivo seja indicar quantos posts estão sendo retornados, o front pode executar um:
`results.length`
Então responder com totalPosts, nesse caso, fica redundante.

2023-08-18 18:36 UTC, PPAKruNN requested changes
O código tá bem escrito, curti bastante.
Tem só algumas coisinhas pra arrumar mesmo, e talvez o uso de três queries não seja 100% necessário, mas primeiro faça funcionar e depois a gente pensa em melhorar as queries.

Ótimo trabalho

2023-08-20 02:52 UTC, maariaclaara commented on src/repositories/posts.repository.js
> +      `SELECT COUNT(*) AS "countPosts" FROM posts WHERE "createdAt" >= $1
Pelo que vi nas aulas, consegue sim

2023-08-20 02:52 UTC, maariaclaara commented on src/controllers/posts.controllers.js
> +      const totalPosts = rows[0].amountPosts;
é p estar com essa variável mesmo, revirei aqui e não achei erro kkkk

2023-08-20 02:53 UTC, maariaclaara commented on src/controllers/posts.controllers.js
> +        nextUrl,
valeuuu!!!! Pedro :)

2023-08-20 02:58 UTC, PPAKruNN approved these changes

2023-08-20 02:58 UTC, merged